checks:
  python: true

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: make tests-readonly
            coverage:
              file: var/tests-coverage.xml
              format: clover
      environment:
        python:
          version: 3.11.10
  dependencies:
    before:
      - pip install -r requirements.txt

filter:
  paths:
    - libredte/*
  excluded_paths:
    - resources/*
    - tests/*
    - tools/*
    - var/*
    - vendor/*