name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      - name: Build Documentation
        run: |
          sphinx-build -b html docs/ docs/_build/html

      - name: Create CNAME file
        run: echo "api-client-python.docs.libredte.cl" > docs/_build/html/CNAME

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          publish_branch: gh-pages
